safe:        false
source:      .
url:         http://localhost

exclude: [README.md, Skeleton] 

destination: ./public_html

future:      true
lsi:         false
highlighter:    null 
markdown:    Kramdown 
permalink:   /:title 

nav:
- page: Home
  permalink: /index.html

- page: Blog
  permalink: /blog.html

- page: Publications
  permalink: /pub.html
