safe:        false
source:      .
url:         http://localhost

exclude: [README.md] 

destination: ./public_html

future:      true
lsi:         false
highlighter:    null 
markdown:    Kramdown 
permalink:   /:title